my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from polls import views


app_name = 'polls'

from django.urls import path
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.details, name='details'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name= 'vote')
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

my_site/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Choice, Question
from django.urls import reverse

# Create your views here.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=int(request.POST['choice']))
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
                                                      'question': question,
                                                      'error_message': 'you did not select a choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=question.id))

polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import Choice, Question
from django.urls import reverse

# Create your views here.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=int(request.POST['choice']))
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
                                                      'question': question,
                                                      'error_message': 'you did not select a choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('polls:results', question_id=question.id)

my_site/polls/templates/polls/details.html
<h1>{{question.question_text}}</h1>
{%if error_message%}
    <p><strong>{{error_message}}</strong></p>
{%endif%}
<form action="{% url 'polls:vote' question.id%}" method="POST">
    {%csrf_token%}
    {%for choice in question.choice_set.all%}
        <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="choice.id"/>
        <label for="choice{{ forloop.counter}}">{{choice.choice_text}}</label><br>
    {%endfor%}
    <input type="submit" value="vote">
</form>

my_site/polls/templates/polls/index.html
{%if latest_question_list%}

    <ul>
        {%for question in latest_question_list%}
        <li>
            <a href="{%url 'polls:details' question_id = question.id%}">{{question.question_text}}</a>
        </li>
        {%endfor%}
    </ul>
{%else%}
    <p>No polls are available</p>
{%endif%}

polls/templates/polls/details.html
<h1>{{question.question_text}}</h1>
{%if error_message%}
    <p><strong>{{error_message}}</strong></p>
{%endif%}
<form action="{% url 'polls:vote' question.id%}" method="POST">
    {%csrf_token%}
    {%for choice in question.choice_set.all%}
        <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{ forloop.counter}}">{{choice.choice_text}}</label><br>
    {%endfor%}
    <input type="submit" value="vote">
</form>

polls/templates/polls/index.html
{%if latest_question_list%}

    <ul>
        {%for question in latest_question_list%}
        <li>
            <a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a>
        </li>
        {%endfor%}
    </ul>
{%else%}
    <p>No polls are available</p>
{%endif%}

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {%endfor%}
</ul>
<a href="{% url 'polls:details' question.id %}">vote again?</a>